pipeline:
  identifier: Build_arrularthar_ui_harness_sample_1709506429825
  name: Build ui-harness-sample
  orgIdentifier: default
  projectIdentifier: asdasd
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1708491840199
        repoName: arrularthar/ui-harness-sample
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      password: <+input>
                      repo: hello/world
                      tags: latest
                      username: <+input>
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
