pipeline:
  identifier: Build_arrularthar_ui_harness_sample_1708878924232
  name: Build ui-harness-sample
  orgIdentifier: default
  projectIdentifier: Harness_POC
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1708491840199
        repoName: arrularthar/ui-harness-sample
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
