pipeline:
  identifier: Build_arrularthar_ui_harness_sample_1709487724500
  name: Build ui-harness-sample
  orgIdentifier: default
  projectIdentifier: POCHarnessUI
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1708491840199
        repoName: arrularthar/ui-harness-sample
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    connectorRef: POCHarness
                    image: node:latest
                    shell: Sh
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Harness-POC
                  identifier: HarnessPOC
                  spec:
                    connectorRef: POCHarness
                    repo: arrulas/harness-poc
                    tags:
                      - harness-go
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        type: CI
